name: Reserve Pickleball Court

on:
  workflow_dispatch:

jobs:
  reserve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Create service account key
        run: echo "$GOOGLE_CREDENTIALS" > service-account-key.json
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Run bot + add to calendar
        run: node bot.js
